import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

import Footer from "@/includes/footer";
import NavigationBar from "@/includes/navigationBar";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen w-screen ${inter.className}`}>
        <ResizablePanelGroup
          direction="horizontal"
          className="flex h-full
        "
        >
          <ResizablePanel
            minSize={10}
            defaultSize={25}
            maxSize={20}
            className="bg-gray-100 z-30"
          >
            <Sidebar />
          </ResizablePanel>
          <ResizableHandle withHandle />

          <ResizablePanel
            collapsible={false}
            defaultSize={100}
            className="relative"
          >
            <div className="h-full w-full overflow-y-auto z-30">
              <NavigationBar />
              {children}
              <Footer />
            </div>
          </ResizablePanel>
        </ResizablePanelGroup>
      </body>
    </html>
  );
}
